### ISSUE TITLE
Ground Elevations added to First Floor Elevations

### ISSUE THREAD

**Issue by JohnRushKucharski** [HydrologicEngineeringCenter/GeoFDA#2]
When first floor elevations are imported as part of the structure inventory ground elevations should not be added to them. Ground elevations should only be added when the ground elevation + foundation height method of computing first floor elevations is requested.

**Comment by HenryGeorgist** [comment]
I will probably need more clarity on this one. 

The first question - are you talking about the step when a user imports or are you talking about data that makes it to the import file to FDA?

Can you provide a bit more context on this one so we fix the right thing?

**Comment by JohnRushKucharski** [comment]
Here's a description of what is happening...
(1) I import the shape file being careful to: (a) NOT click the 'Define Elevation from .shp' radio button, and (b) click the 'Use First Floor Elevation' radio button, (c) select the FF_stage for the FFE column.
(2) The ground elevation is all 0s in the attribute table, and the FFE column shows the correct values.
(3) I compute the import file.
(4) In the import file ground elevations are added and they have been added to the foundation height values (which produces the wrong values)
(5) In the attribute table (back in GeoFDA) it still shows no ground elevation and the expected FFEs  (the desired values).

The desired behavior would be that the .fdai file would contain the FFE values assigned at the time the structure inventory is imported.

You identified the source of the bug (line of code) in an email back on May 1st but I can't find the email containing that line (just reference to you finding it).

**Comment by HenryGeorgist** [comment]
I think it is here:
https://github.com/HydrologicEngineeringCenter/GeoFDA/blob/25806ab798f277f3c7a171e3cfa0e2756984251e/GeoFDA/Output/OutputChildTreeNode.vb#L473

it seems like i have a comment "What if they use FFE?" as I am assigning the Ground elevation from the terrain file.

**Comment by HenryGeorgist** [comment]
It also looks like I am fairly careful about the options in the importer (but possibly make a mistake) - it seems I want the user to define a ground elevation column, but dont do a good job enforcing it.
This is from the code behind the shapefile importer... 
```
        If UseFirstFloorElevation.IsChecked Then
            If CmbFFE.SelectedIndex = -1 OrElse CmbFFE.SelectedIndex = 0 Then
                MsgBox("You did not define a First Floor Elevation, and you did elect to define first floor elevation from the dbf.") : Exit Sub
            Else
                'retrieve from the dbf
                FFE = Array.ConvertAll(dbf.GetColumn(CmbFFE.SelectedItem.ToString), AddressOf Single.Parse)
            End If
        End If

        If UseDbfForTerrain.IsChecked Then
            If CmbGroundElevation.SelectedIndex = -1 OrElse CmbGroundElevation.SelectedIndex = 0 Then MsgBox("You did not define a Ground Elevation, and you did elect to define ground elevation from the dbf.") : Exit Sub
            'update FFE to be the sum of GE and FH
            GE = Array.ConvertAll(dbf.GetColumn(CmbGroundElevation.SelectedItem.ToString), AddressOf Single.Parse)
            If UseFoundationHeight.IsChecked Then
                If CmbFoundationHeight.SelectedIndex = -1 OrElse CmbFoundationHeight.SelectedIndex = 0 Then
                    MsgBox("You did not define a foundation height, and you did elect to define elevation from the dbf.") : Exit Sub
                Else
                    'use FH, Calculate FFE from GE and FH
                    FH = Array.ConvertAll(dbf.GetColumn(CmbFoundationHeight.SelectedItem.ToString), AddressOf Single.Parse)
                    For i = 0 To FH.Count - 1
                        FFE(i) = GE(i) + FH(i)
                        UseDBFGE(i) = UseDbfForTerrain.IsChecked
                        UseFFE(i) = Not UseFoundationHeight.IsChecked
                    Next
                End If
            Else
                'use FFE, FH can be calculated From GE and FFE
                For i = 0 To FFE.Count - 1
                    FH(i) = FFE(i) - GE(i)
                    UseDBFGE(i) = UseDbfForTerrain.IsChecked
                    UseFFE(i) = Not UseFoundationHeight.IsChecked
                Next
            End If
        Else
            'dont use dbf for terrain..
            If UseFoundationHeight.IsChecked Then
                If CmbFoundationHeight.SelectedIndex = -1 OrElse CmbFoundationHeight.SelectedIndex = 0 Then
                    MsgBox("You did not define a foundation height, and you did elect to define elevation from the dbf.") : Exit Sub
                Else
                    'use FH, Calculate FFE from GE and FH
                    FH = Array.ConvertAll(dbf.GetColumn(CmbFoundationHeight.SelectedItem.ToString), AddressOf Single.Parse)
                    For i = 0 To FH.Count - 1
                        FFE(i) = GE(i) + FH(i)
                        UseDBFGE(i) = UseDbfForTerrain.IsChecked
                        UseFFE(i) = Not UseFoundationHeight.IsChecked
                    Next
                End If
            Else
                'use FFE, FH can be calculated From GE and FFE
                For i = 0 To FFE.Count - 1
                    FH(i) = FFE(i) - GE(i)
                    UseDBFGE(i) = UseDbfForTerrain.IsChecked
                    UseFFE(i) = Not UseFoundationHeight.IsChecked
                Next
            End If
        End If
```

**Comment by HenryGeorgist** [comment]
I do not store the selection of the radio button "Use FFE" or "Use FH" - The form also does not have access to the terrain file. 
It seems the design of this form was to build an inventory based on the user selection that has essentially no variation at the time of the "compute". I can propose a workflow, which is essentially to throw a message "User selected First floor elevation and no foundation height or terrain were supplied" and exit.

**Comment by JohnRushKucharski** [comment]
I'm not sure if this answers your question, but I think: (1) if the user's file has a ground elevation it should not be overwritten by the program. I'm not sure if that happens currently, but the comment in your code makes me think it might. (2) if the user imports a FFE one should not be calculated for them. In the case where they import a FFE and have no ground elevations - I also think we should avoid adding a ground elevation to their file (from the terrain data). (3) If they select the foundation height + ground elevation option and they do not import their own ground elevations we should add them (from the terrain file).

**Comment by HenryGeorgist** [comment]
it looks like i store a value on the individual structure record of UseFFE or UseDBFGE which should provide case logic to be able to determine if the user provided GE in the dbf, and if they are using FFE or FH.
From that i should be able to either set ground elevation (if FH and not DBFGE) from the terrain at compute time. or compute FFE from DBFGE and FH, or use FFE directly.

Does this need to be changed in the FDA import file (if FFE is provided but no ground elevation is it ok for me to write 0 for Ground Elevation?)

**Comment by JohnRushKucharski** [comment]
Yes. In that case writing 0 for ground elevation makes sense to me.

**Comment by HenryGeorgist** [comment]
ok. this should be a revision of two different portions of the code, but it should be something that @Brennan1994 could do.

**Comment by HenryGeorgist** [comment]
created item #8 and #9 to handle the two issues at play here. This issue is closing and emphasis is added to #8 and #9
