### ISSUE TITLE
Importing terrain data file limit issue.

### ISSUE THREAD

**Issue by JohnRushKucharski** [HydrologicEngineeringCenter/GeoFDA#3]
There is a bug in GeoFDA that is limiting terrain size on import to 20mb instead of 2000mb (2gb)

This bug is documented on discourse here:  [https://discourse.hecdev.net/t/importing-terrain-file-error/535](url)

**Comment by HenryGeorgist** [comment]
https://github.com/HydrologicEngineeringCenter/GeoFDA/blob/25806ab798f277f3c7a171e3cfa0e2756984251e/GeoFDA/Watershed/Terrain/Forms/TerrainBrowser.xaml.vb#L27

This is the line that needs to be investigated - it is a simple fix,

**Comment by HenryGeorgist** [comment]
@Brennan1994 see if you can make the change (you could do it directly in github if you want) let me know when you want me to review your commit

**Comment by Brennan1994** [comment]
It’s tested with a terrain file size ~250mb. Prior limit was 200mb, new limit is 2gb. In debug I found that the bytes displayed in VS didn’t match what I saw in file explorer . I googled and found that they matched if I converted it to 1kb = 1024bytes. I found what gb should be and included my conversion in the comments.
