### ISSUE TITLE
Depth Grids

### ISSUE THREAD

**Issue by JohnRushKucharski** [HydrologicEngineeringCenter/GeoFDA#5]
The correct depth grid values (values need for assignment to the FDA water surface profiles) are not always being written out the the .fdai file. The issue is documented on discourse here: [https://discourse.hecdev.net/t/geo-fda-wse-vs-depth-grids-output-stages/551/5](url)

**Comment by HenryGeorgist** [comment]
I suspect this one is due to this line:
https://github.com/HydrologicEngineeringCenter/GeoFDA/blob/25806ab798f277f3c7a171e3cfa0e2756984251e/GeoFDA/Hydraulics/Gridded_WSP.vb#L159

in that conditional statement i have no parenthesis. i think the equivalency operation is happening before the plus operation - which will never be "true"

**Comment by HenryGeorgist** [comment]
@Brennan1994 can you try throwing parenthesis around "_Grids(j).GridReader.NoData(0) + invert" and testing?

**Comment by Brennan1994** [comment]
From what I can tell, this function only gets referenced in the function above it, which is not referenced anywhere else. I don't think the code you've identified ever runs in GeoFDA. https://github.com/HydrologicEngineeringCenter/GeoFDA/blob/25806ab798f277f3c7a171e3cfa0e2756984251e/GeoFDA/Hydraulics/Gridded_WSP.vb#L118

**Comment by HenryGeorgist** [comment]
alright. lets take a second look

**Comment by HenryGeorgist** [comment]
you are right - i recommend we clean up that class to remove the methods that have zero references. I think that is createReachFromPoints and combineReachesAndStructures - i will create a new ticket for that action.

the line that needs to be fixed is:
https://github.com/HydrologicEngineeringCenter/GeoFDA/blob/25806ab798f277f3c7a171e3cfa0e2756984251e/GeoFDA/Hydraulics/Gridded_WSP.vb#L252

**Comment by Brennan1994** [comment]
Changes tested with WSP profiles in John Kucharski's NAB GeoFDA model he made for Komla, and on my LWR GeoFDA Study using depth grids. Confirmed -99+1n written for each dry profile at a structure, and invert -2 for the last dry profile at a structure.  Confirmed monotonically increasing values as WSP decrease in probability.
