### ISSUE TITLE
Code Cleanup for GriddedWSP

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/GeoFDA#7]
Please remove the methods CombineReachesandStructures and createReachesFromPoints

This way we will have more clarity on execution paths in the future and can focus our efforts on the right code.

**Comment by Brennan1994** [comment]
Would it be appropriate to delete this outright or comment them out? If they've been rewritten somewhere else it makes more sense to me to delete them all together, but I don't want to squash your code if you think they should be saved.

**Comment by HenryGeorgist** [comment]
Please delete - we can always revert. If you isolate the action to a single commit it is easy to merge back if we ever want to get it back. 
It is best practice to only have code that is required for execution any commented code should be removed and any code that is not executed should be removed. This will make it easier for other people to read and edit the code.
Please delete the code you commented (and thanks for the considerate actions of just commenting)
