### ISSUE TITLE
Do not calculate FH from FFE and GE during Structure Import from shapefile.

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/GeoFDA#8]
https://github.com/HydrologicEngineeringCenter/GeoFDA/blob/bbb1a9de9ff12369afcded5ea4842cf09290e626/GeoFDA/Inventory/Forms/ImportFromShapefile.xaml.vb#L190

starting at this line in the code we do a few things based on the user's input. Please change this code to store the user's input and message if there are improper imputs.

1. if the user imports ground elevations store them
2. if the user imports FFE store them
3. if the user imports FH store them
4. Do not calculate FH from FFE and GE
5. Do not calculete FFE from GE and FH

**Comment by Brennan1994** [comment]
Tested with LWR dataset. Imports verfied by importing FFE, Foundation height/ with and without ground elevations. results in map window match expectations
