### ISSUE TITLE
Compute FFE based off of Data in Structure inventory

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/GeoFDA#9]
During the creation of the fdai file, the structure inventory is loaded from dbf. Check the inventory if FFE is present. If it is, use it.
There should be attributes from the user that declare if the GE was stored in the structure inventory via an atribute. There should also be an attribute about if the user imported an FFE or a FH, use that boolean also.

https://github.com/HydrologicEngineeringCenter/GeoFDA/blob/bbb1a9de9ff12369afcded5ea4842cf09290e626/GeoFDA/Output/OutputChildTreeNode.vb#L473

The line above needs to be only done if necessary - if the FFE is not previously provided, and if the user did not provide ground elevation on structure import.

https://github.com/HydrologicEngineeringCenter/GeoFDA/blob/bbb1a9de9ff12369afcded5ea4842cf09290e626/GeoFDA/Output/OutputChildTreeNode.vb#L474

this line needs to be fixed to only compute FFE if it was not provided and all of the necessary info exists (FH and some source for GE)

if it is not, check the following basic case logic:
1. if the user stored ground elevations on the structure inventory use them (attribute is stored with each structure independently, because user's could be modifying the structure attributes post import)
2. if the user did not store ground elevations or FFE, get ground elevations from the terrain file and add them to foundation heights
3. if the user does not have GE data or FH data at compute time record an error message.

**Comment by Brennan1994** [comment]
Closing. This bug was fixed, but I left the issue open because I was going to further optimize the code around it, but other projects have taken priority recently.
